### ISSUE TITLE
Which features of requirejs are supported?

### ISSUE THREAD

**Issue by drnkwati** [dsheiko/micro-requirejs#4]
Can i load requrejs modules with this?
Will Defining Functions with Dependencies work as well?

**Comment by dsheiko** [comment]
Oh, sorry for the confusing package name. In fact it is not related to RequireJS, it's just a simplest JavaScript loader, that resolves dependencies according to the provided list. It works like Require, but does not provide support for AMD. Instead it serves own very simple module format
